<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="2" failures="0" skipped="0" tests="2" time="1.042" timestamp="2025-10-16T10:55:51.004337" hostname="ANONYMOUS"><testcase classname="" name="tests.api.test_api_2" time="0.000"><error message="collection failure">C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\pathlib.py:567: in import_path
    importlib.import_module(module_name)
C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1387: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1360: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1331: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:935: in _load_unlocked
    ???
C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\assertion\rewrite.py:177: in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\assertion\rewrite.py:359: in _rewrite_test
    tree = ast.parse(source, filename=strfn)
C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\ast.py:50: in parse
    return compile(source, filename, mode, flags,
E     File "C:\python_codes\Automation_modify\AutomationExercise-E2E-Testing-Framework\tests\api\test_api_2.py", line 23
E       """Test POST request to products list API (should return 405)."""
E   IndentationError: expected an indented block after 'try' statement on line 22</error></testcase><testcase classname="" name="tests.api.test_api_3" time="0.000"><error message="collection failure">C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\pathlib.py:567: in import_path
    importlib.import_module(module_name)
C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1387: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1360: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1331: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:935: in _load_unlocked
    ???
C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\assertion\rewrite.py:177: in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\assertion\rewrite.py:359: in _rewrite_test
    tree = ast.parse(source, filename=strfn)
C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\ast.py:50: in parse
    return compile(source, filename, mode, flags,
E     File "C:\python_codes\Automation_modify\AutomationExercise-E2E-Testing-Framework\tests\api\test_api_3.py", line 23
E       """Test GET request to brands list API."""
E   IndentationError: expected an indented block after 'try' statement on line 22</error></testcase></testsuite></testsuites>